### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Lookcatbox** [LMOliver/drawer#2]
关于优先级设置：不论怎么设置都是

任务总数或总大小超出限制，请先提交更多 token

怎么办

**Comment by LMOliver** [comment]
可能因为是您的图太大了，或者您提交了太多任务。

**Comment by Lookcatbox** [comment]
之前就只有一张400px的图片，第二张也是400px，任务只有1个也提交不了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月1日(星期六) 中午1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LMOliver/drawer] 求助 (Issue #2)





 
可能因为是您的图太大了，或者您提交了太多任务。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Lookcatbox** [comment]
是不是把所有用户的任务列表混一起了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月1日(星期六) 中午1:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LMOliver/drawer] 求助 (Issue #2)





 
可能因为是您的图太大了，或者您提交了太多任务。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
